### PR TITLE
feat: add `flip` function

### PR DESCRIPTION
**Pull request by aleclarson**
> [!TIP]
> The owner of this PR can publish a _preview release_ by commenting `/publish` in this PR. Afterwards, anyone can try it out by running `pnpm add radashi@pr<PR_NUMBER>`.

## Description

The `flip` function takes a function and swaps its two arguments. It's most helpful for reversing the order of a comparator (i.e. going from ascending order to descending, or vice versa).

## Checklist

- [ ] Changes are covered by tests if behavior has been changed or added
- [ ] Tests have 100% coverage
- [ ] If code changes were made, the documentation (in the `/docs` directory) has been updated

### CODE REVIEW

**Comment by localusercamp** [comment]
Is there any way to make it work with any number of parameters?

**Comment by aleclarson** [comment]
> Is there any way to make it work with any number of parameters?

If we can keep it performant for the two-argument case, I'd say sure.

Maybe something like this?

```ts
export function flip(fn, argCount = Infinity) {
  return argCount == 2
    ? (a, b) => fn(b, a)
    : argCount == 3
      ? (a, b, c) => fn(c, b, a)
      : (...args) => fn(...args.reverse())
}
```

**Comment by aleclarson** [comment]
Perhaps it might be best to keep it simple (only two arguments) until the demand for more complex use cases is certain.

**Comment by aleclarson** [comment]
Keeping it just the first two arguments, to align with Ramda ([see here](https://github.com/ramda/ramda/blob/v0.30.1/source/flip.js))

**Review by Minhir — APPROVED** [review]

**Pull request merged**
