### PR TITLE
fix: vitest `typecheck`

### LINKED ISSUE #244: Vitest Typecheck is not working
## Description

Hey team, I've noticed that Vitest's [typecheck](https://vitest.dev/guide/testing-types.html) feature doesn't work even though we have `*.test-d.ts` files in the repo.

There are 2 apparent issues:

* We don't check types in `pnpm test` due to not configuring `typecheck` in `vitest.config.ts`. [It's disabled by default](https://vitest.dev/config/#typecheck-enabled).
* Enabling `typecheck` in `vitest.config.ts` causes typecheck tests to pass blindly, even where there are failing tests.

## How to reproduce

1. Run `pnpm test`. You will notice that `*.test-d.ts` files are not reported.
2. In an attempt to enable typecheck, add the following entry to `vitest.config`:

```diff
import { defineConfig } from 'vitest/config'

const resolve = (specifier: string) =>
  new URL(import.meta.resolve(specifier)).pathname

export default defineConfig(env => ({
  test: {
    globals: true,
    include: ['tests/**/*.test.ts'],
    benchmark: {
      include: ['benchmarks/**/*.bench.ts'],
    },
    coverage: {
      thresholds: { 100: true },
      include: ['src/**'],
    },
    setupFiles: env.mode === 'benchmark' ? ['benchmarks/globals.ts'] : [],

+    typecheck: {
+      include: ['tests/**/*.test-d.ts'],
+      enabled: true,
+    },
  },
  resolve: {
    alias: {
      radashi: resolve('./src/mod.js'),
    },
  },
}))

```
3. Run `pnpm test` again. It looks like all `*.test-d.ts` tests are now reported, and pass!
4. Add a bogus test, purposefully failing type test to one of the `*.test-d.ts` files, say `select.test-d.ts`:

```diff
import * as _ from 'radashi'

describe('select types', () => {
+  test('bogus test to test vitest', () => {
+    expectTypeOf<number>().toEqualTypeOf<string>()
+  })
  test('select with condition', () => {
    const array = [
      { id: 1, name: 'John' },
      { id: 2, name: 'Jane' },
      { id: 3, name: null },
    ]
    const result = _.select(
      array,
      item => item.name,
      item => item.name !== null,
    )
    // No way for TypeScript to understand that the result is a string[]
    expectTypeOf(result).toEqualTypeOf<(string | null)[]>()
  })
  test('select without condition', () => {
    const array = [
      { id: 1, name: 'John' },
      { id: 2, name: 'Jane' },
      { id: 3, name: null },
    ]
    const result = _.select(array, item => item.name)
    expectTypeOf(result).toEqualTypeOf<string[]>()
  })
})
```
5. Run `pnpm test` again, all `*.test-d.ts` tests still pass.

## Questions

1. Is this not the correct way to test types, is there something I missed?

## Attempted fixes

1. Update Vitest to latest - that alone did not solve the issue for me.
2. After narrowing down against a working minimal example, I've identified that the issue is in `tsconfig.json`. The following change fixes the issue:

```diff
{
-  "include": ["src/**/*.ts"],
+  "include": ["src/**/*.ts", "tests/**/*.test-d.ts"],
  "compilerOptions": {
    "allowImportingTsExtensions": true,
    "moduleResolution": "node",
    "outDir": "./dist/tmp",
    "noEmitOnError": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "isolatedDeclarations": true,
    "target": "es2017",
    "lib": ["es2017"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "strict": true,
    "paths": {
      "radashi": ["./src/mod.ts"]
    },
-    "types": []
+    "types": ["vitest/globals"]
  }
}
```

However, this doesn't seem ideal, as the `tsconfig.json` in `tests` implies we should configure tests there and not the root `tsconfig.json`.

Note that solution (2) requires solution (1). It only works with an updated vitest.

**Edit:** I think I found a good, minimal solution in #245

### PR DESCRIPTION
**Pull request by yamcodes**
> [!TIP]
> The owner of this PR can publish a _preview release_ by commenting `/publish` in this PR. Afterwards, anyone can try it out by running `pnpm add radashi@pr<PR_NUMBER>`.

## Summary

Fix Vitest `typecheck` by (1) updating Vitest (2) enabling `typecheck` (3) pointing typecheck to the tests tsconfig

All 3 avenues must be applied together, omitting one causes `type-d.ts` files either to pass blindly (false negatives) or not report at all.

## Related issue, if any:

Closes #244 

## For any code change,

- [ ] Related documentation has been updated, if needed
- [ ] Related tests have been added or updated, if needed
- [ ] Related benchmarks have been added or updated, if needed

## Does this PR introduce a breaking change?

No

## Bundle impact

| Status | File | Size [^1337] | Difference |
| --- | --- | --- | --- |
| M | `src/array/merge.ts` | 185 | -25 (-12%) |

[^1337]: Function size includes the `import` dependencies of the function.

### CODE REVIEW

**Comment by yamcodes** [comment]
After experimenting with Vitest versions, we need at least [`v2.1.0-beta.6`](https://github.com/vitest-dev/vitest/releases/tag/v2.1.0-beta.6). It seems like the following PR fixed the false negatives: https://github.com/vitest-dev/vitest/pull/6256

**Review by MarlonPassos-git — APPROVED** [review]
Thanks for the PR, I had seen this issue before but hadn't taken the time to fix it.

I tested it in a codespace, and it seems to work fine now, thanks.

Even though type checking is still in beta (I think that was one of the reasons why it wasn't active), it would be worth validating it in the CI stage.

**Comment by MarlonPassos-git** [comment]
@yamcodes just one thing, fix the PR title for “fix: vitest `typecheck`”

**Comment by yamcodes** [comment]
Thanks, @MarlonPassos-git, I agree. There is no point in having code in the codebase we can't use on the main branch. Given the existence of `*.test-d.ts` files on the branch, we should have a way to use them.

**Comment by aleclarson** [comment]
This is great 😄 Thanks a lot, @yamcodes

**Pull request merged**
