### PR TITLE
chore: add v12.2.0 release notes

### PR DESCRIPTION
**Pull request by aleclarson**
The release notes for v12.2.0, a work in progress. I've created a `release-notes` branch, which this PR targets, so I could open a PR tracking my progress and inviting collaboration. This should help keep the process open and transparent. These release notes will also exist in the GitHub Releases section upon completion.

What's needed:
- ~More/better code examples~ (edit: Now that we link to the docs, this isn't as big of a deal. Just make sure the example previews the core functionality.)
- Check for missing commits (excluding `chore` commits)
- Ensure all PR/commit links are inside the headings
- General proof-reading and refinement

### Long-term solution

I used [this script](https://github.com/radashi-org/radashi/tree/main/scripts/release-notes) to generate the initial draft. The generated draft saved a lot of time, but I've since edited it quite a bit. I think there's still room for improvement in that script, so less editing is needed in the future. Specifically, including an example of desired output would help a lot, I think.

### CODE REVIEW

**Comment by MarlonPassos-git** [comment]
Hey @aleclarson, do you intend to keep a version.md file for all future versions?

**Comment by aleclarson** [comment]
@MarlonPassos-git Yeah that's the plan. Why do you ask?

**Comment by MarlonPassos-git** [comment]
> @MarlonPassos-git Yeah that's the plan. Why do you ask?

And I was thinking that over time it might get a bit messy having a large number of {version}.md files at the root of the project. This isn’t something I usually see in projects; they typically group them into a documentation folder or something similar.

**Comment by aleclarson** [comment]
Oh I think you misread what I wrote up top. 😄  As you can see, this PR is targeting a `release-notes` branch, which is where they'll be kept.

**Comment by aleclarson** [comment]
Just now, I've refined many of the sections from the beginning until `isRegExp` (which still needs refinement itself). If anyone wants to contribute to this PR, please use the same formatting that I've gone with in those sections.

**Comment by aleclarson** [comment]
I've done more work on this today. I'm down to line 782!

**Comment by MarlonPassos-git** [comment]
🥳

**Pull request merged**
